nodeLinker: node-modules

packageExtensions:
  "@algolia/autocomplete-core@*":
    peerDependencies:
      "@algolia/client-search": ">=4.9.1 <6"
      algoliasearch: ">=4.9.1 <6"
      search-insights: ">=1 <3"

  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependencies:
      "@algolia/client-search": ">=4.9.1 <6"
      algoliasearch: ">=4.9.1 <6"

  "@docsearch/react@*":
    dependencies:
      "@algolia/client-search": "^5.37.0"
      algoliasearch: "^5.37.0"
      search-insights: "^2.0.0"

  "@docusaurus/babel@*":
    peerDependencies:
      react: "^18.0.0 || ^19.0.0"
      react-dom: "^18.0.0 || ^19.0.0"

  "@docusaurus/bundler@*":
    peerDependencies:
      react: "^18.0.0 || ^19.0.0"
      react-dom: "^18.0.0 || ^19.0.0"

  "@docusaurus/plugin-content-blog@*":
    peerDependencies:
      "@mdx-js/react": "^3.0.0"

  "@docusaurus/plugin-content-docs@*":
    peerDependencies:
      "@mdx-js/react": "^3.0.0"

  "@docusaurus/plugin-content-pages@*":
    peerDependencies:
      "@mdx-js/react": "^3.0.0"

  "@docusaurus/plugin-css-cascade-layers@*":
    peerDependencies:
      "@mdx-js/react": "^3.0.0"
      react: "^18.0.0 || ^19.0.0"
      react-dom: "^18.0.0 || ^19.0.0"

  "@docusaurus/plugin-debug@*":
    peerDependencies:
      "@mdx-js/react": "^3.0.0"

  "@docusaurus/plugin-google-analytics@*":
    peerDependencies:
      "@mdx-js/react": "^3.0.0"

  "@docusaurus/plugin-google-gtag@*":
    peerDependencies:
      "@mdx-js/react": "^3.0.0"

  "@docusaurus/plugin-google-tag-manager@*":
    peerDependencies:
      "@mdx-js/react": "^3.0.0"

  "@docusaurus/plugin-sitemap@*":
    peerDependencies:
      "@mdx-js/react": "^3.0.0"

  "@docusaurus/plugin-svgr@*":
    peerDependencies:
      "@mdx-js/react": "^3.0.0"

  "@docusaurus/preset-classic@*":
    peerDependencies:
      "@mdx-js/react": "^3.0.0"

  "@docusaurus/theme-search-algolia@*":
    peerDependencies:
      "@mdx-js/react": "^3.0.0"
    dependencies:
      search-insights: "^2.0.0"

  "@docusaurus/utils-common@*":
    peerDependencies:
      react: "^18.0.0 || ^19.0.0"
      react-dom: "^18.0.0 || ^19.0.0"

  "@docusaurus/utils-validation@*":
    peerDependencies:
      react: "^18.0.0 || ^19.0.0"
      react-dom: "^18.0.0 || ^19.0.0"

  "@docusaurus/utils@*":
    peerDependencies:
      react: "^18.0.0 || ^19.0.0"
      react-dom: "^18.0.0 || ^19.0.0"

  "@typescript-eslint/utils@*":
    peerDependencies:
      typescript: "*"

  "bybit-api@*":
    peerDependencies:
      typescript: "*"
