FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY apps ./apps
COPY packages ./packages
COPY examples ./examples

RUN corepack enable && corepack prepare yarn@4.12.0 --activate
RUN yarn install --immutable
RUN yarn workspace @tradejs/docs build

FROM nginx:stable-alpine

COPY nginx/nginx.docs.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/apps/docs/build /usr/share/nginx/html

EXPOSE 80

