services:
  ml-infer:
    build:
      context: .
      dockerfile: Dockerfile.infer
    ports:
      - "8000:8000"
    environment:
      MODEL_DIR: /app/data/ml/models
      DEFAULT_STRATEGY: default
    volumes:
      - ./ml:/app/ml
      - ./data:/app/data
