services:
  ml:
    build:
      context: .
      dockerfile: Dockerfile.ml
    volumes:
      - ./ml:/app/ml
      - ./data:/app/data
    working_dir: /app
    command: ["python", "/app/ml/train.py", "--help"]

  ml-profile:
    build:
      context: .
      dockerfile: Dockerfile.ml.profile
    volumes:
      - ./ml:/app/ml
      - ./data:/app/data
    working_dir: /app
    command: ["python", "/app/ml/profile.py", "--help"]
