const nextJest = require('next/jest');

const createJestConfig = nextJest({ dir: './apps/app' });

const customJestConfig = {
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  collectCoverageFrom: [
    'apps/app/src/**/*.{ts,tsx}',
    'packages/*/src/**/*.{ts,tsx}',
    '!**/__tests__/**',
    '!**/*.test.{ts,tsx}',
    '!**/*.spec.{ts,tsx}',
    '!**/*.d.ts',
  ],
  coverageThreshold: {
    './apps/app/src/': {
      statements: 37,
      branches: 32,
      functions: 33,
      lines: 38,
    },
    './packages/cli/src/': {
      statements: 60,
      branches: 52,
      functions: 63,
      lines: 61,
    },
    './packages/connectors/src/': {
      statements: 67,
      branches: 57,
      functions: 61,
      lines: 70,
    },
    './packages/core/src/': {
      statements: 90,
      branches: 76,
      functions: 92,
      lines: 92,
    },
    './packages/create-tradejs/src/': {
      statements: 54,
      branches: 40,
      functions: 54,
      lines: 54,
    },
    './packages/indicators/src/': {
      statements: 96,
      branches: 83,
      functions: 100,
      lines: 100,
    },
    './packages/infra/src/': {
      statements: 77,
      branches: 54,
      functions: 81,
      lines: 79,
    },
    './packages/node/src/': {
      statements: 84,
      branches: 70,
      functions: 82,
      lines: 84,
    },
    './packages/types/src/': {
      statements: 95,
      branches: 85,
      functions: 100,
      lines: 97,
    },
  },
  moduleNameMapper: {
    '^@tradejs/connectors$': '<rootDir>/packages/connectors/src/index',
    '^@tradejs/core/api$': '<rootDir>/packages/core/src/api',
    '^@tradejs/core/async$': '<rootDir>/packages/core/src/async',
    '^@tradejs/core/backtest$': '<rootDir>/packages/core/src/backtest',
    '^@tradejs/core/config$': '<rootDir>/packages/core/src/config',
    '^@tradejs/core/constants$': '<rootDir>/packages/core/src/constants',
    '^@tradejs/core/data$': '<rootDir>/packages/core/src/data',
    '^@tradejs/core/figures$': '<rootDir>/packages/core/src/figures',
    '^@tradejs/core/indicators$': '<rootDir>/packages/core/src/indicators',
    '^@tradejs/core/math$': '<rootDir>/packages/core/src/math',
    '^@tradejs/core/strategies$': '<rootDir>/packages/core/src/strategies',
    '^@tradejs/core/tickers$': '<rootDir>/packages/core/src/tickers',
    '^@tradejs/core/trade$': '<rootDir>/packages/core/src/trade',
    '^@tradejs/core/time$': '<rootDir>/packages/core/src/time',
    '^@tradejs/node/ai$': '<rootDir>/packages/node/src/ai',
    '^@tradejs/node/backtest$': '<rootDir>/packages/node/src/backtest',
    '^@tradejs/node/cli$': '<rootDir>/packages/node/src/cli',
    '^@tradejs/node/connectors$': '<rootDir>/packages/node/src/connectors',
    '^@tradejs/node/constants$': '<rootDir>/packages/node/src/constants',
    '^@tradejs/node/pine$': '<rootDir>/packages/node/src/pine',
    '^@tradejs/node/registry$': '<rootDir>/packages/node/src/registry',
    '^@tradejs/node/strategies$': '<rootDir>/packages/node/src/strategies',
    '^@tradejs/infra/(.*)$': '<rootDir>/packages/infra/src/$1',
    '^@tradejs/indicators/range-geometry$':
      '<rootDir>/packages/indicators/src/range-geometry',
    '^@tradejs/indicators$': '<rootDir>/packages/indicators/src/index',
    '^@tradejs/types$': '<rootDir>/packages/types/src/index',
    '^@tradejs/types/(.*)$': '<rootDir>/packages/types/src/$1',
    '^#app/(.*)$': '<rootDir>/apps/app/src/app/$1',
    '^#actions/(.*)$': '<rootDir>/apps/app/src/app/actions/$1',
    '^#store$': '<rootDir>/apps/app/src/app/store/index',
    '^#constants$': '<rootDir>/packages/core/src/constants/index',
    '^#shared/(.*)$': '<rootDir>/apps/app/src/app/components/Shared/$1',
    '^#utils/(.*)$': '<rootDir>/packages/core/src/utils/$1',
    '^#ui$': '<rootDir>/apps/app/src/app/components/UI/index',
    '^#components/(.*)$': '<rootDir>/apps/app/src/app/components/$1',
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
  },
  testMatch: ['**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[jt]s?(x)'],
  testPathIgnorePatterns: [
    '<rootDir>/.ai/',
    '<rootDir>/e2e/',
    '<rootDir>/dist/',
    '<rootDir>/packages/.*/dist/',
    '<rootDir>/packages/cli/src/scripts/test.ts',
  ],
  testEnvironment: 'jest-environment-jsdom',
};

module.exports = createJestConfig(customJestConfig);
