import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/ai.ts',
    'src/backtestArtifacts.ts',
    'src/coreResearch.ts',
    'src/files.ts',
    'src/http.ts',
    'src/logger.ts',
    'src/ml.ts',
    'src/redis.ts',
    'src/runtimeStrategyConfigs.ts',
    'src/runtimeDeployments.ts',
    'src/strategyReleaseEvidence.ts',
    'src/userSettings.ts',
    'src/timescale/client.ts',
    'src/timescale/candles.ts',
    'src/timescale/derivatives.ts',
    'src/timescale/hyperliquidWhales.ts',
    'src/timescale/marketContext.ts',
    'src/timescale/spread.ts',
    'src/tradingAccounts.ts',
  ],
  format: ['cjs', 'esm'],
  dts: true,
  tsconfig: './tsconfig.build.json',
  clean: true,
  outDir: 'dist',
  target: 'node24',
  external: [
    '@grpc/grpc-js',
    '@grpc/proto-loader',
    '@tradejs/types',
    'chalk',
    'ioredis',
    'pg',
    'winston',
  ],
});
