server:
  address: tcp://0.0.0.0:9091

log:
  level: info

default_redirection_url: https://redisinsight.aleksnick01inv.fvds.ru/

totp:
  issuer: "Investing"

jwt_secret: "5b915f5d0c07d264ed1217445c959535c34bbf1e4228aabd77138869081994c2"

session:
  name: authelia_session
  same_site: lax
  secret: "643f4dcd792f8414afbab7e428f1a7f1ade348af821d76342b891cb3ebd31614"
  expiration: 3600
  inactivity: 300
  remember_me_duration: 1M
  domain: aleksnick01inv.fvds.ru
  redis:
    host: redis
    port: 6379
    database_index: 2

storage:
  local:
    path: /config/db/storage.sqlite3
  encryption_key: "9dbd1281207087b1456b397f394ebc14b97cdb94ac5d129d064be3958e8aa335"

authentication_backend:
  password_reset:
    disable: true
  file:
    path: /config/users.yml
    password:
      algorithm: argon2id

access_control:
  default_policy: deny
  rules:
    - domain: redisinsight.aleksnick01inv.fvds.ru
      policy: one_factor

notifier:
  filesystem:
    filename: /config/notification.txt
