import { Interval } from '@types';

export const config = {
  INTERVAL: '15' as Interval,
  LIMIT: 100,
  MA_FAST: 14,
  MA_SLOW: 85,
  ATR_PERIOD: 15,
  ATR_OPEN: 0.6,
  ATR_CLOSE: 1.3,
  BB_PERIOD: 13,
  BB_STDDEV: 2,
  OBV_SMA_PERIOD: 75,
  BREAKOUT_LOOKBACK: 20,
  RSI_PERIOD: 14,
  RSI_CHANNEL: [30, 70],
  MOM_PERIOD: 10,
  BB_SQUEEZE_LOOKBACK: 5,
  BB_SQUEEZE_THRESHOLD: 0.5,
  REQUIRE_SQUEEZE_BEFORE_BREAKOUT: true,
  REQUIRED_SCORE_LONG: 4,
  REQUIRED_SCORE_SHORT: 4,
  TP_LONG: [
    { profit: 0.1, rate: 0.25 },
    { profit: 0.2, rate: 0.5 },
  ],
  TP_SHORT: [
    { profit: 0.05, rate: 0.25 },
    { profit: 0.1, rate: 0.5 },
  ],
  SL_LONG: 0.06,
  SL_SHORT: 0.03,
  CONDITION_WEIGHTS: {
    smaTrend: 1,
    obvTrend: 1,
    bbBreakout: 1,
    momDirection: 1,
    rsiInRange: 1,
    hadSqueeze: 1,
    priceBreakout: 2,
  },
};
