import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/api.ts',
    'src/async.ts',
    'src/backtest.ts',
    'src/cli.ts',
    'src/config.ts',
    'src/connectors.ts',
    'src/constants.ts',
    'src/data.ts',
    'src/figures.ts',
    'src/indicators.ts',
    'src/json.ts',
    'src/math.ts',
    'src/pine.ts',
    'src/strategies.ts',
    'src/tickers.ts',
    'src/time.ts',
  ],
  format: ['cjs', 'esm'],
  dts: true,
  tsconfig: '../../tsconfig.build.json',
  clean: true,
  outDir: 'dist',
  target: 'node20',
  external: [
    '@langchain/core',
    '@langchain/openai',
    '@tradejs/infra',
    '@tradejs/types',
    'bybit-api',
    'chalk',
    'date-fns',
    'ioredis',
    'klinecharts',
    'lodash',
    'pg',
    'pinets',
    'progress',
    'puppeteer',
    'technicalindicators',
    'uuid',
  ],
});
