import { Interval, TrendLineOptions } from '@types';

export const config = {
  ENV: 'BACKTEST',
  INTERVAL: '15' as Interval,
  MAKE_ORDERS: true,
  CLOSE_OPPOSITE_POSITIONS: false,
  ML_THRESHOLD: 0.15,
  MAX_LOSS_VALUE: 10,
  MAX_CORRELATION: 0.45,
  MA_FAST: 14,
  MA_MEDIUM: 49,
  MA_SLOW: 50,
  OBV_SMA: 10,
  ATR: 14,
  ATR_PCT_SHORT: 7,
  ATR_PCT_LONG: 30,
  BB: 20,
  BB_STD: 2,
  MACD_FAST: 12,
  MACD_SLOW: 26,
  MACD_SIGNAL: 9,
  LEVEL_LOOKBACK: 20,
  LEVEL_DELAY: 2,
  TRENDLINE: {
    minTouches: 4,
    offset: 3,
  } as Partial<TrendLineOptions>,
  HIGHS: {
    enable: false,
    direction: 'LONG',
    TP: 4.4,
    SL: 1.6,
    minRiskRatio: 2,
  },
  LOWS: {
    enable: true,
    direction: 'LONG',
    TP: 2.9,
    SL: 0.95,
    minRiskRatio: 2,
  },
} as const;
