/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NativeCandle {
  timestamp: number
  open: number
  high: number
  low: number
  close: number
  volume: number
  turnover?: number
  takerBuyBaseVolume?: number
  takerSellBaseVolume?: number
}
export declare function buildBaseContextOverlayJson(candles: Array<NativeCandle>, price: number, previousPrice?: number | undefined | null, atr?: number | undefined | null): string
